// <auto-generated />
using System;
using CollabTechFile.DbContextCollab;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollabTechFile.Migrations
{
    [DbContext(typeof(CollabTechFileContext))]
    [Migration("20251014175107_CollabTechFile")]
    partial class CollabTechFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CollabTechFile.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<int?>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("texto");

                    b.HasKey("IdComentario")
                        .HasName("PK__Comentar__DDBEFBF969871F15");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Comentario");
                });

            modelBuilder.Entity("CollabTechFile.Models.Documento", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.Property<DateOnly?>("Prazo")
                        .HasColumnType("date")
                        .HasColumnName("prazo");

                    b.Property<bool>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Versao")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("versao");

                    b.Property<int>("VersaoAtual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IdDocumento")
                        .HasName("PK__Document__E52073477EF6EE36");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Documento");
                });

            modelBuilder.Entity("CollabTechFile.Models.DocumentoVersoes", b =>
                {
                    b.Property<int>("IdDocumentoVersoes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumentoVersoes"));

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<int>("NumeroVersao")
                        .HasColumnType("int");

                    b.HasKey("IdDocumentoVersoes")
                        .HasName("PK__Document__82F8A7D2227FA4DC");

                    b.HasIndex("IdDocumento");

                    b.ToTable("DocumentoVersoes");
                });

            modelBuilder.Entity("CollabTechFile.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.HasKey("IdEmpresa")
                        .HasName("PK__Empresa__5EF4033E44C59B40");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("CollabTechFile.Models.Feedback", b =>
                {
                    b.Property<int>("IdFeedback")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFeedback"));

                    b.Property<DateTime?>("DataEnvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("data_envio")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.HasKey("IdFeedback")
                        .HasName("PK__Feedback__408FF1038053A229");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("CollabTechFile.Models.Regra", b =>
                {
                    b.Property<int>("IdRegras")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegras"));

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nome");

                    b.HasKey("IdRegras")
                        .HasName("PK__Regras__8905AC384135C0B8");

                    b.ToTable("Regras");
                });

            modelBuilder.Entity("CollabTechFile.Models.RegrasDoc", b =>
                {
                    b.Property<int>("IdRegrasDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRegras_Doc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegrasDoc"));

                    b.Property<int?>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<int?>("IdRegras")
                        .HasColumnType("int");

                    b.HasKey("IdRegrasDoc")
                        .HasName("PK__Regras_D__31F46840051EB162");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdRegras");

                    b.ToTable("Regras_Doc");
                });

            modelBuilder.Entity("CollabTechFile.Models.ReqDoc", b =>
                {
                    b.Property<int>("IdReqDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdReq_Doc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReqDoc"));

                    b.Property<int?>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<int?>("IdRequisito")
                        .HasColumnType("int");

                    b.HasKey("IdReqDoc")
                        .HasName("PK__Req_Doc__06347D59F6F0E5AE");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdRequisito");

                    b.ToTable("Req_Doc");
                });

            modelBuilder.Entity("CollabTechFile.Models.Requisito", b =>
                {
                    b.Property<int>("IdRequisito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRequisito"));

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("IdRequisito")
                        .HasName("PK__Requisit__661FC7C2E926C8A0");

                    b.ToTable("Requisitos");
                });

            modelBuilder.Entity("CollabTechFile.Models.Suporte", b =>
                {
                    b.Property<int>("IdSuporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSuporte"));

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdSuporte")
                        .HasName("PK__Suporte__AA104D73D97D94F0");

                    b.ToTable("Suporte");
                });

            modelBuilder.Entity("CollabTechFile.Models.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("TituloTipoUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdTipoUsuario")
                        .HasName("PK__TipoUsua__CA04062B57B6CA9A");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("CollabTechFile.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<string>("Empresa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("empresa");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuario__5B65BF97D000312F");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CollabTechFile.Models.Comentario", b =>
                {
                    b.HasOne("CollabTechFile.Models.Documento", "IdDocumentoNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdDocumento")
                        .HasConstraintName("FK__Comentari__IdDoc__5BE2A6F2");

                    b.HasOne("CollabTechFile.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Comentarios")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Comentari__IdUsu__5AEE82B9");

                    b.Navigation("IdDocumentoNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CollabTechFile.Models.Documento", b =>
                {
                    b.HasOne("CollabTechFile.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Documentos")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK__Documento__IdUsu__5812160E");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CollabTechFile.Models.DocumentoVersoes", b =>
                {
                    b.HasOne("CollabTechFile.Models.Documento", "IdDocumentoNavigation")
                        .WithMany("DocumentoVersos")
                        .HasForeignKey("IdDocumento")
                        .IsRequired()
                        .HasConstraintName("DocumentoVersao");

                    b.Navigation("IdDocumentoNavigation");
                });

            modelBuilder.Entity("CollabTechFile.Models.Feedback", b =>
                {
                    b.HasOne("CollabTechFile.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("feedbackUsuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CollabTechFile.Models.RegrasDoc", b =>
                {
                    b.HasOne("CollabTechFile.Models.Documento", "IdDocumentoNavigation")
                        .WithMany("RegrasDocs")
                        .HasForeignKey("IdDocumento")
                        .HasConstraintName("FK__Regras_Do__IdDoc__6754599E");

                    b.HasOne("CollabTechFile.Models.Regra", "IdRegrasNavigation")
                        .WithMany("RegrasDocs")
                        .HasForeignKey("IdRegras")
                        .HasConstraintName("FK__Regras_Do__IdReg__66603565");

                    b.Navigation("IdDocumentoNavigation");

                    b.Navigation("IdRegrasNavigation");
                });

            modelBuilder.Entity("CollabTechFile.Models.ReqDoc", b =>
                {
                    b.HasOne("CollabTechFile.Models.Documento", "IdDocumentoNavigation")
                        .WithMany("ReqDocs")
                        .HasForeignKey("IdDocumento")
                        .HasConstraintName("FK__Req_Doc__IdDocum__619B8048");

                    b.HasOne("CollabTechFile.Models.Requisito", "IdRequisitoNavigation")
                        .WithMany("ReqDocs")
                        .HasForeignKey("IdRequisito")
                        .HasConstraintName("FK__Req_Doc__IdRequi__60A75C0F");

                    b.Navigation("IdDocumentoNavigation");

                    b.Navigation("IdRequisitoNavigation");
                });

            modelBuilder.Entity("CollabTechFile.Models.Usuario", b =>
                {
                    b.HasOne("CollabTechFile.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("FK__Usuario__IdEmpre__5535A963");

                    b.HasOne("CollabTechFile.Models.TipoUsuario", "IdTipoUsuarioNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoUsuario")
                        .HasConstraintName("FK__Usuario__IdTipoU__5441852A");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdTipoUsuarioNavigation");
                });

            modelBuilder.Entity("CollabTechFile.Models.Documento", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("DocumentoVersos");

                    b.Navigation("RegrasDocs");

                    b.Navigation("ReqDocs");
                });

            modelBuilder.Entity("CollabTechFile.Models.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CollabTechFile.Models.Regra", b =>
                {
                    b.Navigation("RegrasDocs");
                });

            modelBuilder.Entity("CollabTechFile.Models.Requisito", b =>
                {
                    b.Navigation("ReqDocs");
                });

            modelBuilder.Entity("CollabTechFile.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CollabTechFile.Models.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Documentos");

                    b.Navigation("Feedbacks");
                });
#pragma warning restore 612, 618
        }
    }
}
